export class std {
  static cout: (message: any) => void;
  static cin: (message?: string) => string;
  static endl: string;
  static pair: any;
  static tuple: any;
  static array: any;
  static queue: any;
  static stack: any;
  static priority_queue: any;
  static deque: any;
  static list: any;
  static forward_list: any;
  static multiset: any;
  static multimap: any;
  static unordered_set: any;
  static unordered_map: any;
  static unordered_multiset: any;
  static unordered_multimap: any;
  static bitset: any;
  static valarray: any;
  static slice: any;
  static regex: any;
  static atomic: any;
  static condition_variable: any;
  static future: any;
  static shared_mutex: any;
  static shared_timed_mutex: any;
  static unique_lock: any;
  static lock_guard: any;
  static scoped_lock: any;
  static once_flag: any;
  static call_once: any;
  static bind: any;
  static function: any;
  static mem_fn: any;
  static ref: any;
  static cref: any;
  static reference_wrapper: any;
  static bad_function_call: any;
  static default_searcher: any;
  static boyer_moore_searcher: any;
}
